### ISSUE TITLE
Pathfinding broken?

### ISSUE THREAD

**Issue by netmute** [collinhover/impactplusplus#46] opened 2013-08-25 13:09 UTC
I have an entity that should find it's path to a point in another room. It can only get there by climbing a ladder, which it does, but it doesn't go up all the way. Instead, it tries to move right into the platform it should be walking on.

This is the situation:
![bildschirmfoto 2013-08-25 um 15 01 04](https://f.cloud.github.com/assets/574582/1022389/003eebc0-0d87-11e3-9763-a1495c5c3fe7.png)

The entity basically gets stuck in that position, endlessly moving up and down a tiny bit.

**Comment by collinhover** [comment] 2013-08-25 13:59
That point in the screenshot is getting flagged as a corner, and there is special behavior in place to try and get around corners without getting stuck. However, this tends to work best when the character is between 1 to 3 tiles in size. What looks to be happening here is that the character is moving and cannot get to where it needs to be before another pathfinding tick refreshes the path.

I've not had a chance to test the pathfinding on characters that are so much larger than the tile size. I have tested entities that are between 1 to 3 tiles in size, but larger than that will require some recursive searching.

My suggestion until I (or someone else) has time to tackle super large entities is to draw out a pathfinding map in the editor and avoid the tiles that border on solid tiles, which can help quite a bit. You can also try to only find the path once before the character starts moving to the next point.

**Comment by collinhover** [comment] 2013-08-25 14:17
Let me explain a bit more about pathfinding maps... set a layer's name to "pathfinding" in the editor to have the game automatically set it as a pathfinding map, and use the tileset "media/pathfindingtiles_plusplus_*.png" that comes with Impact++. In your case, draw green pathfinding tiles on the ladders (but not on the gaps next to them), as well as a little more than half a character height above the floor.

![pathfinding_map](https://f.cloud.github.com/assets/1005377/1022533/d7888fbe-0d96-11e3-9897-02f38a26c367.png)

This should fix the issue.

**Comment by racingcow** [comment] 2013-08-26 12:52
Thanks for the explanation, Collin. I have the same issue (32x32 entities and 8x8 collision tiles, and this should help. I didn't know about pathfinding map support until now. I'll give that a try.

**Comment by collinhover** [comment] 2013-08-26 14:40
In case someone does want to try to fix this, the relevant methods are (in execution order):

ig.Character.findMoveToPath()
https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/abstractities/character.js#L935

ig.pathfinding.getPathTo()
https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/helpers/pathfinding.js#L741

ig.Character.moveToPath()
https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/abstractities/character.js#L1178

Pathfinding already accounts for entities that are bigger than the tilesize, and only allows them to walk straight nodes if the current node is touching an unwalkable node (so the entity doesn't get caught going diagonal). Another check could be inserted, if the entity is larger than 3 tiles in any direction, to completely skip any nodes that are NOT surrounded by 8 walkable nodes, right around https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/helpers/pathfinding.js#L896, which may fix this issue without the need for pathfinding maps.

**Comment by racingcow** [comment] 2013-08-26 21:35
I'll try and take a look tonight.

**Comment by netmute** [comment] 2013-08-27 09:39
Thanks for the explanation of pathfinding maps Collin!

I implemented them, but now pathfinding stops working completely. The entity isn't able to find a path at all. I marked the entire map as 'green' just to try if it works then, but got the same result.

**Comment by collinhover** [comment] 2013-08-27 13:21
@netmute that is surprising. And when you removed the pathfinding map, pathfinding worked again?

**Comment by netmute** [comment] 2013-08-27 13:28
@collinhover Exactly.

**Comment by collinhover** [comment] 2013-08-27 14:22
@netmute I just tested pathfinding without and with a pathfinding map added in the editor, on the most ridiculous platforming I could think of, without any problems. The bot was able to follow me best with the pathfinding map, but in both cases did fine. I can't reproduce the issue =( can you please send me a test case where it is doing what you describe?

**Comment by netmute** [comment] 2013-08-28 05:23
@collinhover I'll dig into it tonight. Will try to reproduce it on a blank game, or I'll find the cause in my game. Either way, it's going to be fun ;)

**Comment by racingcow** [comment] 2013-08-29 19:40
Just a quick update from me: I tried implementing [your suggested solution](https://github.com/collinhover/impactplusplus/issues/46#issuecomment-23266880) above, but didn't have much luck. It didn't seem to have any affect on the pathfinding.

Another thing I tried was to check all surrounding nodes (a block around the current node roughly the size of my entity), and skip the current node if any one of those nodes weren't walkable. The result was that the entity wouldn't chase me down corridors that were narrower than the height of the entity. I suspect this is because I was using the max of the entity's height/width to do the calculations.

I decided to fall back to drawing a pathfinding map, but I am having the [same trouble](https://github.com/collinhover/impactplusplus/issues/46#issuecomment-23323866) described by @netmute. The creature selects its prey, and EntityExtended.moveTo gets called, but it never actually chases the player.

I'll see if I can figure anything out by simplifying the map in my game.

**Comment by collinhover** [comment] 2013-08-29 19:58
I'm wondering if the stuck state is getting fired and the path is getting dropped. Can you check if this is happening? The relevant line is https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/abstractities/character.js#L1199

Edit: is the creature getting a path from the `findMoveToPath` method? It gets stored in the `path` property of the creature.

**Comment by collinhover** [comment] 2013-08-29 20:32
@racingcow any chance you can send me the code for the game you are using that is not working with the pathfinding maps?

**Comment by racingcow** [comment] 2013-08-29 21:33
Ah, I finally found out what my issue was. As it turns out, I can't read, apparently. :wink: I'm not sure if @netmute is having the same issue or not, but in my case the issue was that I had the tile size on the collision layer set to 8, while the tile size on the pathfinding layer was set to 32

While not in the [r5 documentation](http://collinhover.github.io/impactplusplus/ig.PathfindingMap.html) on the trunk, it is clearly stated that I shouldn't be doing that in the [pathfinding-map.js code](https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/pathfinding-map.js#L18) in the dev branch.

Sorry for the confusion @collinhover, and to @netmute for hijacking the thread if you are having a different issue.

**Comment by collinhover** [comment] 2013-08-29 21:47
@racingcow oh! Thanks for keeping with such an obscure bug. I'm going to write several warnings in the docs right now and have the pathfinding throw an error if the tilesizes don't match. Apologies for that not being in the docs.

On a side note, did the pathfinding map actually help once it was working?

**Comment by racingcow** [comment] 2013-08-29 22:08
The pathfinding map definitely helped. The way my level design is set up, there are still a couple of places I think I'll need to use the other colors or rearrange things a bit, but I think with a bit of work I can use it to prevent my creatures from getting hung up on the corners/edges of my collision map.

Speaking of that, what do the other colors on that map do? It looks like the red x prevents a tile from being eligible as a pathfinding node, but what do the yellow and dark green ones do?

**Comment by collinhover** [comment] 2013-08-29 22:28
The map adds weight to nodes, where the max weight added is based on `ig.CONFIG.PATHFINDING.WEIGHT`. By default, all nodes get the maximum weight, so they are all equally good, and the collision map is used to determine if a node is walkable. A node's weight doesn't matter if it is not walkable. 

The default pathfinding map tiles all have a weight percent attached to them, where the brightest green is 0 (no weight = best), the dark green is 0.25 (25% = good), the yellow is 0.75 (75% = not so good), and no pathfinding map tile is 1 (100% = worst). The red X is unwalkable, as you mentioned, and the other two were original intended to tell the creature that they really should jump at this node. However, I need to remove those because the path following code jumps really well on its own at this point (edit: doing that right now). From my experience, a good pathfinding map can make pathfinding much faster as it will naturally try the cheap nodes and do far fewer checks.

**Comment by racingcow** [comment] 2013-08-30 02:38
Thanks for the explanation, @collinhover!

**Comment by netmute** [comment] 2013-08-30 09:09
Nice find @racingcow. That might be my problem as well. The collisionMap size is 4px and the pathfindingMap is 8px. Will try tonight.

**Closed as completed** 2013-09-26 00:29 UTC
Labels: enhancement
