### ISSUE TITLE
UIInteractive - activate method not working with Ejecta

### ISSUE THREAD

**Issue by lzaiats** [collinhover/impactplusplus#9] opened 2013-06-03 16:14 UTC
I am writing my code like this:

{

ig.UIButton = ig.UIInteractive.extend({

```
animSheet: new ig.AnimationSheet( 'media/shared/button_help.png', 52, 46 ),
animSettings: true,

activate: function ( entity ) {
    this.parent();
    console.log('*');
    // nothing happens when i click (touch) the button...
},

alwaysToggleActivate: true
```

});

MyGame = ig.GameExtended.extend({

```
init: function() {
    this.parent();

    var btn = this.spawnEntity(ig.UIButton,  10, (ig.system.height - 46 - 10));
},

update: function() {
    this.parent();

    ig.game.pause();
},

draw: function() {
    this.parent();
}
```

});

}

When i run this code on Ejecta and i click (touch) the button, nothing happens... I don't know if i am using it the wrong way or if it's not working properly... :)

**Comment by collinhover** [comment] 2013-06-03 16:24
Thanks for posting the issue. Some questions to help us figure this out:
1. Do you have a player entity in the game?
2. Does it work in the browser, i.e. not using Ejecta?

edit: I have a feeling the first question is the problem. I just made a test level with no player and a button, and the button does not work. It appears I built the interaction with a button into the 'abstractities/player' class, which is fine when you have a player entity, but not fine when the player entity does not exist.

**Comment by lzaiats** [comment] 2013-06-03 16:27
I don't have a player entity, because i am writing my main menu interface right now and i am not supposed to have a player on screen :)

I am programming directly on Ejecta, but i can try on the browser...

**Comment by collinhover** [comment] 2013-06-03 16:28
Yeah the problem is not on your end, it is the way that Impact++ fundamentally handles interaction and requires the player entity. This is actually a bad design on my part. I will work on a fix today and push to the dev branch as soon as I can.

**Comment by lzaiats** [comment] 2013-06-03 16:39
Hmmm... OK! I will wait :)

**Comment by collinhover** [comment] 2013-06-03 18:31
Okay, on the dev branch UI interaction is now inside the game class, which fixes the bad design decisions. I tested several UI elements, pausing game, changing levels, using player abilities, etc, and it appears to be error free on my end. This does change some of the API unfortunately, but it is necessary. Does this fix the issue for you?

**Comment by lzaiats** [comment] 2013-06-03 19:22
Hmmm... Ive updated my lib with the dev tree and it's still not working... If you can give me a simple scenario of a Game instantiating a UIInteractive and handling the "click/touch" event would be nice! Sorry for the inconvenience, but i still can't get this working...

**Comment by collinhover** [comment] 2013-06-03 21:02
Its not an inconvenience!

Using the "Getting Started" code at: http://collinhover.github.io/impactplusplus/

Try the following in your "main.js" module ( or wherever you extend ig.GameExtended):

```
var game = ig.GameExtended.extend({

                init: function () {

                    this.parent();

                    // load level

                    this.loadLevel(ig.global.LevelTest);

                    // add pause button in bottom left corner of screen

                    var pauseToggle = ig.game.spawnEntity(ig.UITogglePause, 0, 0, {
                        posPct: { x: 1, y: 1 },
                        align: { x: 1, y: 1 },
                        margin: { x: 0.02, y: 0.02 }
                    });

                }

            });
```

I have no player in the test level and when I click the pause toggle button everything works as expected. That said, it does require a level to work, and I have no menus in the game I've been working on... but UI should not require a level I think. Do you not have a level loaded?

**Comment by collinhover** [comment] 2013-06-03 21:09
I've changed it so UI elements work without a level. Can you try again now?

**Comment by collinhover** [comment] 2013-06-06 15:15
Assuming this is fixed with recent commits. Please reopen issue if not!

**Closed as completed by collinhover** 2013-06-06 15:15 UTC
Labels: bug
