### ISSUE TITLE
Pathfinding and slopes == bug?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#69] opened 2013-09-30 14:04 UTC
It seems to me that one of my Characters are unable to jump up to a slope.
If I change that slope to a regular square block, it works fine. He jumps up.

**Comment by arakash92** [comment] 2013-09-30 14:08
Here's a video of the issue: http://www.screenr.com/GykH

**Comment by collinhover** [comment] 2013-10-01 00:35
This is an interesting bug. I believe it is caused by the character's path following treating slopes as safe and not needing a jump. I didn't expect anyone to use slopes like you're using them in the video... I'll need to change it to only treat some slopes as safe.

**Comment by collinhover** [comment] 2013-10-01 02:41
I didn't have enough time to finish testing this, but it appears that the issue is also possibly caused by the path following using the center of the entity as the from point. It should probably use the bottom of the entity instead (i.e. the feet). However, for entities that are the same height as a single tile, it is more likely the slopes issue.

**Comment by collinhover** [comment] 2013-10-01 23:42
I'm reworking pathfinding to account for both issues at the moment, hope to have a commit ready to test today our tomorrow.

**Comment by arakash92** [comment] 2013-10-02 00:17
Awesome!

**Comment by collinhover** [comment] 2013-10-03 02:29
Okay, everything is working pretty smoothly on my end. I've just got one last thing to tweak, then I'll push it. Turning out to be a rather large overhaul.

**Comment by arakash92** [comment] 2013-10-03 05:29
ok! looking forward to try it out :)

**Comment by arakash92** [comment] 2013-10-03 21:55
Hm, did you push those last changes?

I just got the latest dev branch and the grounded property is fixed but my characters slide like it's on ice :P

**Comment by collinhover** [comment] 2013-10-03 22:04
Nope,I'll close this issue when I've pushed the fixes. If you still have sliding then we'll check it out.

**Comment by collinhover** [comment] 2013-10-04 18:55
Have not had enough time to fully test the changes, but basic testing results are good on my end.

**Closed as completed by collinhover** 2013-10-04 18:55 UTC
Labels: bug

**Comment by arakash92** [comment] 2013-10-06 00:45
Cool I'll test it!
